# Generated by Django 5.2.1 on 2025-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Akın', max_length=100)),
                ('last_name', models.CharField(default='Tanrıverdi', max_length=100)),
                ('email', models.EmailField(default='akntanrverdi2@gmail.com', max_length=254)),
                ('phone_number', models.CharField(default='05380891401', max_length=20)),
                ('job_title', models.CharField(default='Information Systems Engineer', max_length=100)),
                ('bio', models.TextField(default='Passionate about technology and development, with a focus on IT systems. Enthusiastic learner and problem solver.')),
            ],
        ),
    ]
